<?php

declare(strict_types=1);

namespace MyProject\Component\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241114190628 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Verifica que la plataforma sea PostgreSQL 12
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        // Crear los esquemas si no existen
        $this->addSql('CREATE SCHEMA IF NOT EXISTS public');
        $this->addSql('CREATE SCHEMA IF NOT EXISTS catalogo');
        $this->addSql('CREATE SCHEMA IF NOT EXISTS seguridad');


        $this->addSql('CREATE TABLE catalogo.sistemas (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(128) NOT NULL, descripcion VARCHAR(256) NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_7afca61d69d2337e ON catalogo.sistemas (codigo_interno)');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE catalogo.servicios_productos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(128) NOT NULL, descripcion VARCHAR(256) NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_99d38a4169d2337e ON catalogo.servicios_productos (codigo_interno)');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE catalogo.lista_catalogo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descripcion VARCHAR(128) NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE catalogo.tipo_servicios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(128) NOT NULL, descripcion VARCHAR(256) NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cef42fe669d2337e ON catalogo.tipo_servicios (codigo_interno)');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE seguridad.usuarios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre_usuario VARCHAR(64) NOT NULL, contrasenia VARCHAR(512) NOT NULL, nombres VARCHAR(64) NOT NULL, apellidos VARCHAR(64) NOT NULL, correo VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, isadmin BOOLEAN DEFAULT false NOT NULL, estado BOOLEAN DEFAULT true NOT NULL, id_tipo_usuario_permiso INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_f35f304177040bc9 ON seguridad.usuarios (correo)');
        $this->addSql('CREATE UNIQUE INDEX uniq_f35f3041d67cf11d ON seguridad.usuarios (nombre_usuario)');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE seguridad.permisos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(128) NOT NULL, accion VARCHAR(128) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, descripcion TEXT DEFAULT NULL, codigo_interno VARCHAR(64) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_f1edbc5069d2337e ON seguridad.permisos (codigo_interno)');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE catalogo.tipo_usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(128) NOT NULL, descripcion VARCHAR(256) NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_db9e826c69d2337e ON catalogo.tipo_usuario (codigo_interno)');

        $this->addSql('CREATE TABLE seguridad.tipo_usuario_permisos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, descripcion VARCHAR(512) NOT NULL, codigo_interno VARCHAR(64) NOT NULL, usuario_id INT DEFAULT NULL, tipo_usuario_id INT DEFAULT NULL, permiso_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_347481184abe41b6 ON seguridad.tipo_usuario_permisos (tipo_usuario_id)');
        $this->addSql('CREATE INDEX idx_347481186cefad37 ON seguridad.tipo_usuario_permisos (permiso_id)');
        $this->addSql('CREATE INDEX idx_34748118db38439e ON seguridad.tipo_usuario_permisos (usuario_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_3474811869d2337e ON seguridad.tipo_usuario_permisos (codigo_interno)');
        $this->addSql('ALTER TABLE seguridad.tipo_usuario_permisos ADD CONSTRAINT fk_34748118db38439e FOREIGN KEY (usuario_id) REFERENCES seguridad.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguridad.tipo_usuario_permisos ADD CONSTRAINT fk_347481184abe41b6 FOREIGN KEY (tipo_usuario_id) REFERENCES catalogo.tipo_usuario (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguridad.tipo_usuario_permisos ADD CONSTRAINT fk_347481186cefad37 FOREIGN KEY (permiso_id) REFERENCES seguridad.permisos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE catalogo.lista_catalogo_detalle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_lista_catalogo INT NOT NULL, id_valor INT NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_f927f77dc00c6618 ON catalogo.lista_catalogo_detalle (id_valor)');
        $this->addSql('CREATE INDEX idx_f927f77dcffc2dc3 ON catalogo.lista_catalogo_detalle (id_lista_catalogo)');
        $this->addSql('ALTER TABLE catalogo.lista_catalogo_detalle ADD CONSTRAINT fk_f927f77dcffc2dc3 FOREIGN KEY (id_lista_catalogo) REFERENCES catalogo.lista_catalogo (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE catalogo.zona (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(128) NOT NULL, descripcion VARCHAR(256) NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_8378db6e69d2337e ON catalogo.zona (codigo_interno)');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE seguridad.zona_usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_zona INT NOT NULL, id_usuario INT NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_b2a2628969d2337e ON seguridad.zona_usuario (codigo_interno)');
        $this->addSql('CREATE INDEX idx_b2a262892ca6181c ON seguridad.zona_usuario (id_zona)');
        $this->addSql('CREATE INDEX idx_b2a26289fcf8192d ON seguridad.zona_usuario (id_usuario)');
        $this->addSql('ALTER TABLE seguridad.zona_usuario ADD CONSTRAINT fk_b2a262892ca6181c FOREIGN KEY (id_zona) REFERENCES catalogo.zona (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguridad.zona_usuario ADD CONSTRAINT fk_b2a26289fcf8192d FOREIGN KEY (id_usuario) REFERENCES seguridad.usuarios (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE catalogo.horario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(128) NOT NULL, descripcion VARCHAR(256) NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, inicio TIME(0) WITHOUT TIME ZONE NOT NULL, fin TIME(0) WITHOUT TIME ZONE NOT NULL, estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ea0c3d1c69d2337e ON catalogo.horario (codigo_interno)');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE catalogo.servicios_productos_detalles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(128) NOT NULL, descripcion VARCHAR(256) NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, id_sistemas INT DEFAULT NULL, id_tipo_servicios INT DEFAULT NULL, id_servicios_productos INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_b8c753be69d2337e ON catalogo.servicios_productos_detalles (codigo_interno)');
        $this->addSql('CREATE INDEX idx_b8c753be1f768267 ON catalogo.servicios_productos_detalles (id_tipo_servicios)');
        $this->addSql('CREATE INDEX idx_b8c753be71f1b0fb ON catalogo.servicios_productos_detalles (id_sistemas)');
        $this->addSql('CREATE INDEX idx_b8c753bed0c6e90b ON catalogo.servicios_productos_detalles (id_servicios_productos)');
        $this->addSql('ALTER TABLE catalogo.servicios_productos_detalles ADD CONSTRAINT fk_b8c753be71f1b0fb FOREIGN KEY (id_sistemas) REFERENCES catalogo.sistemas (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE catalogo.servicios_productos_detalles ADD CONSTRAINT fk_b8c753be1f768267 FOREIGN KEY (id_tipo_servicios) REFERENCES catalogo.tipo_servicios (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE catalogo.servicios_productos_detalles ADD CONSTRAINT fk_b8c753bed0c6e90b FOREIGN KEY (id_servicios_productos) REFERENCES catalogo.servicios_productos (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE catalogo.detalle_zona_servicio_horario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_servicios_productos_detalles INT NOT NULL, id_horario INT NOT NULL, id_zona_usuario INT NOT NULL, nombre VARCHAR(128) NOT NULL, descripcion VARCHAR(256) NOT NULL, codigo_interno VARCHAR(64) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_57f5f402e27c971b ON catalogo.detalle_zona_servicio_horario (id_zona_usuario)');
        $this->addSql('CREATE UNIQUE INDEX uniq_57f5f40269d2337e ON catalogo.detalle_zona_servicio_horario (codigo_interno)');
        $this->addSql('CREATE INDEX idx_57f5f4023cc5fad3 ON catalogo.detalle_zona_servicio_horario (id_horario)');
        $this->addSql('CREATE INDEX idx_57f5f402b0ae95b2 ON catalogo.detalle_zona_servicio_horario (id_servicios_productos_detalles)');
        $this->addSql('ALTER TABLE catalogo.detalle_zona_servicio_horario ADD CONSTRAINT fk_57f5f402e27c971b FOREIGN KEY (id_zona_usuario) REFERENCES seguridad.zona_usuario (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE catalogo.detalle_zona_servicio_horario ADD CONSTRAINT fk_57f5f4023cc5fad3 FOREIGN KEY (id_horario) REFERENCES catalogo.horario (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE catalogo.detalle_zona_servicio_horario ADD CONSTRAINT fk_57f5f402b0ae95b2 FOREIGN KEY (id_servicios_productos_detalles) REFERENCES catalogo.servicios_productos_detalles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE control_estadisticos_servicios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, cantidad_firmada INT DEFAULT 0 NOT NULL, cantidad_anulada INT DEFAULT 0 NOT NULL, fecha_corte TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, id_detalle_zona_servicio_horario INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_152bf6235e4bd1ef ON control_estadisticos_servicios (id_detalle_zona_servicio_horario)');
        $this->addSql('CREATE UNIQUE INDEX uniq_152bf623d17f50a6 ON control_estadisticos_servicios (uuid)');
        $this->addSql('ALTER TABLE control_estadisticos_servicios ADD CONSTRAINT fk_152bf6235e4bd1ef FOREIGN KEY (id_detalle_zona_servicio_horario) REFERENCES catalogo.detalle_zona_servicio_horario (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE configuracion_servicios_estadisticos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, json_configuracion JSON NOT NULL, fecha_corte TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado BOOLEAN DEFAULT true NOT NULL, id_configuracion_servicios_estadisticos INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_1486d2f12dc86ecb ON configuracion_servicios_estadisticos (id_configuracion_servicios_estadisticos)');
        $this->addSql('ALTER TABLE configuracion_servicios_estadisticos ADD CONSTRAINT fk_1486d2f12dc86ecb FOREIGN KEY (id_configuracion_servicios_estadisticos) REFERENCES control_estadisticos_servicios (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE catalogo.sistemas');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE catalogo.servicios_productos');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE catalogo.lista_catalogo');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE catalogo.tipo_servicios');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE seguridad.usuarios');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE seguridad.tipo_usuario_permisos');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE catalogo.lista_catalogo_detalle');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE configuracion_servicios_estadisticos');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE catalogo.detalle_zona_servicio_horario');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE catalogo.zona');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE seguridad.zona_usuario');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE catalogo.horario');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE control_estadisticos_servicios');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE catalogo.servicios_productos_detalles');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE seguridad.permisos');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE catalogo.tipo_usuario');
    }
}
