doctrine:
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

    types:
        uuid: Ramsey\Uuid\Doctrine\UuidType
        jsonb: Doctrine\DBAL\Types\JsonType
